from autolife_planning.dataclass.robot_description import CameraConfig, RobotConfig

autolife_robot_config = RobotConfig(
    urdf_path="/media/run/Extend/Autolife-Planning/assets/robot/autolife/autolife.urdf",
    joint_names=[
        "Joint_Ankle",
        "Joint_Knee",
        "Joint_Waist_Pitch",
        "Joint_Waist_Yaw",
        "Joint_Left_Shoulder_Inner",
        "Joint_Left_Shoulder_Outer",
        "Joint_Left_UpperArm",
        "Joint_Left_Elbow",
        "Joint_Left_Forearm",
        "Joint_Left_Wrist_Upper",
        "Joint_Left_Wrist_Lower",
        "Joint_Right_Shoulder_Inner",
        "Joint_Right_Shoulder_Outer",
        "Joint_Right_UpperArm",
        "Joint_Right_Elbow",
        "Joint_Right_Forearm",
        "Joint_Right_Wrist_Upper",
        "Joint_Right_Wrist_Lower",
    ],
    camera=CameraConfig(
        link_name="Link_Camera_Chest",
        width=640,
        height=480,
        fov=60.0,
        near=0.1,
        far=10.0,
    ),
)

HOME_JOINTS = [
    0.0887,
    -0.0293,
    -0.0128,
    -0.0424,
    -0.0700,
    0.1110,
    0.1234,
    -0.0488,
    -0.1148,
    -0.0954,
    0.1303,
    -0.1605,
    -0.2033,
    0.0565,
    -0.0134,
    -0.0278,
    0.1667,
    -0.0103,
]
